from __future__ import annotations
from typing import Protocol, Any, Dict, List

class Repository(Protocol):
    def with_rls_user(self, user: str) -> "Repository": ...
    def server_version(self) -> str: ...
    def get_presence(self, samplenumber: str) -> Dict[str, Any] | None: ...
    def list_entries(self, table: str, samplenumber: str) -> List[Dict[str, Any]]: ...
    def search_samples(self, q: str, limit: int) -> List[str]: ...
    def filter_samples(
        self,
        table: str,
        measured_by: str | None,
        type: str | None,
        fraction: str | None,
        limit: int,
    ) -> List[str]: ...